### ISSUE TITLE
Kotlin language is not supported

### ISSUE THREAD

**Issue by vitorhansen** [mkoslacz/MoviperTemplateGenerator#24]
When i go to generate screen and create a VIPER model with Kotlin language, all of files are created with .java

**Comment by mkoslacz** [comment]
That's correct. When we want to create a new VIPER files set we just use the current generator (that is obviously generating the java files, as you mentioned) and we convert it to Kotlin using Android Studio.

Moviper 3.0 is coming soon and actually I doubt that we would re-create the Android Studio Template generator as it is right now, as Android Studio template, because of the problems with ftl files development. We couldn't find testing tools for that, bugs in ftl script causes Android Studio to break what forces the developer to restart the IDE what is **really** time consuming, etc. That overall causes this kind of development to be the real pain in the neck.

Probably this generator will be recreated in the simple and clean way - as the command line tool.

I sincerely apologize for replying late to your issue. If you have any doubts do not hesitate to reopen the issue.
